ExpenseWallet/Models/ErrorViewModel.cs
namespace ExpenseWallet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpenseWallet/Controllers/StitchServiceController.cs
using Core.ExpenseWallet;
using Core.ExpenseWallet.Data;
using Core.ExpenseWallet.Interfaces;
using Core.ExpenseWallet.Models;
using Core.ExpenseWallet.Utilities;
using Core.ExpenseWallet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace ExpenseWallet.Controllers
{
    public class StitchServiceController : Controller
    {
        private readonly ILogger<StitchServiceController> _logger;
        private readonly IUrlService _urlService;
        private readonly IWalletService _walletService;
        private readonly IFloatService _floatService;
        private readonly IStitchSettings _settings;
        private readonly IPaymentService _paymentService;

        public StitchServiceController(ILogger<StitchServiceController> logger, IUrlService urlService, IWalletService walletService, IFloatService floatService, IStitchSettings settings, IPaymentService paymentService)
        {
            _logger = logger;
            _urlService = urlService;
            _walletService = walletService;
            _floatService = floatService;
            _settings = settings;
            _paymentService = paymentService;
        }

        public async Task<IActionResult> Index()
        {
            var link = await _urlService.BuildUrl(new RedirectUrlModel() { AuthorizationUrl = _settings.AuthorizeUrl });
            return Redirect(link);
        }
        [HttpGet]
        [Route("return")]
        public async Task<IActionResult> Wallet(AuthenticationResponseModel responseModel)
        {
            ExpenseWalletView vm = Default.GetDefaultExpenseWalletView();
            try
            {
                vm = await _walletService.GetExpenseWalletView(responseModel.Code);
            }
            catch(Exception ex)
            {
                _logger.LogError($"An exception happened while getting the wallet {ex}");
            }
            return View(vm);
        }
        public IActionResult TopUp()
        {
            var vm = new TopUpViewModel() { Message = string.Empty };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> TopUp(TopUpViewModel topUpViewModel)
        {
            try
            {
                if (!IsValidTopUpModel(topUpViewModel)) { return View(topUpViewModel); }
                var result = await AddFloatTopUp(topUpViewModel);
                if (!string.IsNullOrEmpty(result))
                {
                    return Redirect(result);
                }
            }
            catch(Exception ex)
            {
                _logger.LogError($"An exception happened while topping up the account {ex}");
            }
            return RedirectToAction("WalletTopUps");
        }
        public IActionResult WalletTopUps()
        {
            TopUpWalletView vm = Default.GetDefaultTopUpWalletView();
            try {
                vm = _walletService.GetTopUpWalletView();
            }
            catch(Exception ex)
            {
                _logger.LogError($"An exception happened while getting the wallet top ups {ex}");
            }
            
            return View(vm);
        }
        public async Task<IActionResult> ExpenseBreakDown()
        {
            TransactionCategoryView vm = Default.GetDefaultTransactionCategoryView;
            try
            {
                vm = await _walletService.GetTransactionCategoryView();
            }
            catch(Exception ex)
            {
                _logger.LogError($"An exception happened while getting the expense breakdown {ex}");
            }
            
            return View(vm);
        }
        [Route("HandleMfaTopUp")]
        [HttpGet]
        public IActionResult HandleMfaTopUp(MfaTopUpResponseModel mfaTopUpResponseModel)
        {
            try
            {
                _floatService.AddFloatPayment(mfaTopUpResponseModel);
            }
            catch(Exception ex)
            {
                _logger.LogError($"An exception happened while mfa top uo {ex}");
            }
           
            return RedirectToAction("WalletTopUps");
        }
        private bool IsValidTopUpModel(TopUpViewModel topUpViewModel)
        {
            var isValidTopUp = false;
            try
            {
                var isValidAmount = SecurityUtilities.IsValidAmount(topUpViewModel.Amount);
                var isValidReference = SecurityUtilities.IsValidReference(topUpViewModel.Reference);
                if (!isValidAmount) { ModelState.AddModelError("Amount", "Amount is required and cannot be less than 0.01"); }
                if (!isValidReference) { ModelState.AddModelError("Reference", "Reference is required, it must be less than 20 chars and cannot contain special characters"); }
                isValidTopUp = isValidAmount || isValidReference;
            }
            catch (Exception ex)
            {
                _logger.LogError($"An error happened while validating the top up view model {ex}");
            }
            return isValidTopUp;
        }

        private async Task<string> AddFloatTopUp(TopUpViewModel topUpViewModel)
        {
            
            var currentFloatBalance = _floatService.GetFloatBalance();
            var amount = Convert.ToDouble(topUpViewModel.Amount, CultureInfo.InvariantCulture);
            var floatPayment = new FloatPayment()
            {
                Amount = Math.Round(amount, 2, MidpointRounding.AwayFromZero),
                Reference = topUpViewModel.Reference,
                Balance = Math.Round(currentFloatBalance + amount, 2, MidpointRounding.AwayFromZero),
                CreatedDate = DateTime.UtcNow,
                Id = Guid.NewGuid(),
                Currency = Default.DefaultCurrency
            };
            var stitchResponse = await _paymentService.GetPaymentInitiation(floatPayment);
            if (stitchResponse.HasErrors)
            {
                var mfaAuthUrl = _paymentService.GetMultifactorPaymentIniationUrl(stitchResponse);
                return mfaAuthUrl;
            }
            await _floatService.AddFloatPayment(floatPayment,stitchResponse);
            return string.Empty;
        }
    }
}

ExpenseWallet/Views/Shared/Components/_Footer.cshtml
<div class="row">
    <div class="col-12">
        <footer class="footer py-4  ">
            <div class="container-fluid">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col-lg-6 mb-lg-0 mb-4">
                        <div class="copyright text-center text-sm text-muted text-lg-start">
                            © <script>
                                  document.write(new Date().getFullYear())
                            </script>,
                            made with <i class="fa fa-heart"></i> by
                            Expense Wallet
                            for a better money management.
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                            <li class="nav-item">
                                <a asp-action="Wallet" asp-controller="StitchService" class="nav-link text-muted" target="_blank">Wallet</a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Wallet" asp-controller="StitchService" class="nav-link text-muted" target="_blank">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="ExpenseBreakDown" asp-controller="StitchService" class="nav-link text-muted" target="_blank">Expense Breakdown</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>

ExpenseWallet/Views/Shared/Components/_Nav.cshtml
  <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Dashboard</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Dashboard</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <label class="form-label">Type here...</label>
              <input type="text" class="form-control">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <a href="../pages/sign-in.html" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Sign In</span>
              </a>
            </li>
            <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
            <li class="nav-item px-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0">
                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
              </a>
            </li>
            <li class="nav-item dropdown pe-2 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-bell cursor-pointer"></i>
              </a>
              <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="/expensewallet/img/team-2.jpg" class="avatar avatar-sm  me-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">New message</span> from Laur
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          13 minutes ago
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="../assets/img/small-logos/logo-spotify.svg" class="avatar avatar-sm bg-gradient-dark  me-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">New album</span> by Travis Scott
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          1 day
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="avatar avatar-sm bg-gradient-secondary  me-3  my-auto">
                        <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                          <title>credit-card</title>
                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                              <g transform="translate(1716.000000, 291.000000)">
                                <g transform="translate(453.000000, 454.000000)">
                                  <path class="color-background" d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z" opacity="0.593633743"></path>
                                  <path class="color-background" d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"></path>
                                </g>
                              </g>
                            </g>
                          </g>
                        </svg>
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          Payment successfully completed
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          2 days
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->

ExpenseWallet/Views/Shared/Components/_SideBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
        <img src="/expensewallet/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">Wallet</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white" asp-action="Wallet" asp-controller="StitchService">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="ExpenseBreakDown" asp-controller="StitchService">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <img src="/expensewallet/img/icons8-money-48.png" style="width:25px; height:18px;background: white;"/>
            </div>
            <span class="nav-link-text ms-1"> Expense Breakdown</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="WalletTopUps" asp-controller="StitchService">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">receipt_long</i>
            </div>
            <span class="nav-link-text ms-1">Top Ups</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="Wallet" asp-controller="StitchService">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">view_in_ar</i>
            </div>
            <span class="nav-link-text ms-1">Virtual Reality</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="Wallet" asp-controller="StitchService">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
            </div>
            <span class="nav-link-text ms-1">RTL</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="Wallet" asp-controller="StitchService">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">notifications</i>
            </div>
            <span class="nav-link-text ms-1">Notifications</span>
          </a>
        </li>
        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="../pages/profile.html">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">person</i>
            </div>
            <span class="nav-link-text ms-1">Profile</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="../pages/sign-in.html">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">login</i>
            </div>
            <span class="nav-link-text ms-1">Sign In</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="../pages/sign-up.html">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">assignment</i>
            </div>
            <span class="nav-link-text ms-1">Sign Up</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
      <div class="mx-3">
        <a class="btn bg-gradient-primary mt-4 w-100" href="https://www.creative-tim.com/product/material-dashboard-pro?ref=sidebarfree" type="button">Upgrade to pro</a>
      </div>
    </div>
  </aside>

ExpenseWallet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/expensewallet/img/favicon.png">
    <title>
        Expense Wallet App - @ViewBag.Title
    </title>
    <link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css" />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Nucleo Icons -->
    <link href="/expensewallet/css/nucleo-icons.css" rel="stylesheet" />
    <link href="/expensewallet/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- CSS Files -->
    <link id="pagestyle" href="/expensewallet/css/material-dashboard.css?v=3.0.4" rel="stylesheet" />


</head>
<body class="g-sidenav-show bg-gray-200">
    @{
        await Html.RenderPartialAsync("/Views/Shared/Components/_Sidebar.cshtml");
    }
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        @{
            await Html.RenderPartialAsync("/Views/Shared/Components/_Nav.cshtml");
        }
        <div class="container-fluid py-4">
            @RenderBody()
        </div>
    </main>

    <script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExpenseWallet/Views/StitchService/TopUp.cshtml
@model TopUpViewModel
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 style="text-align:center;">
                Top Up Wallet
            </h1>
        </div>
        <hr style="height: 2px; border: 2px solid #344767;" />
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-body">
                    <div class="row" style="margin-bottom:10px;">
                        <div class="col-12">
                            <h4>Adding funds to your wallet has never been easier</h4>
                        </div>
                    </div>

                    <form role="form" method="post" class="text-start" asp-action="TopUp" asp-controller="StitchService">
                        <div class="input-group input-group-outline my-3">
                            <input type="text" class="form-control" asp-for="Amount" placeholder="Amount" required>
                        </div>
                        <span asp-validation-for="Amount" class="text-danger"></span>
                        <div class="input-group input-group-outline mb-3">
                            <input type="text" class="form-control" asp-for="Reference" placeholder="Reference" id="referenceId" required>
                        </div>
                        <span asp-validation-for="Reference" class="text-danger"></span>
                        <div class="form-check form-switch d-flex align-items-center mb-3">
                            <input class="form-check-input" type="checkbox" id="autoGenRef" onclick="AutoGenerateReference()">
                            <label class="form-check-label mb-0 ms-3" for="rememberMe">Create Reference For Me</label>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Submit</button>
                        </div>
                    </form>
                    @if (Model.HasError)
                    {
                        <span class="text-danger">@Model.Message</span>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        function generateRef(length) {
            let result = 'REF';
            const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
            const charactersLength = characters.length;
            for (let i = 0; i < length; i++) {
                result += characters.charAt(Math.floor(Math.random() * charactersLength));
            }

            return result;
        }

        function AutoGenerateReference() {
            var isChecked = $('#autoGenRef').is(":checked");
            if (isChecked) {
                var ref = generateRef(6)
                $('#referenceId').val(ref);
            }
            else {
                $('#referenceId').val("");
            }
        }
    </script>
}

ExpenseWallet/Views/StitchService/WalletTopUps.cshtml
@using Core.ExpenseWallet.Interfaces
@using Core.ExpenseWallet.Utilities
@model TopUpWalletView
@inject IStitchSettings _stitchSettings
@{
     var topUpUrl = _stitchSettings.RedirectUrls.Last().Replace("return", "LinkAccount");
}
<div class="row" style="margin-bottom:30px;">

    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
            <div class="card-header p-3 pt-2">
                <div class="icon icon-lg icon-shape bg-gradient-dark shadow-dark text-center border-radius-xl mt-n4 position-absolute">
                    <i class="material-icons opacity-10">weekend</i>
                </div>
                <div class="text-end pt-1">
                    <p class="text-sm mb-0 text-capitalize">Wallet Balance</p>
                    <h4 class="mb-0">@Model.FloatBalance</h4>
                </div>
            </div>
            <hr class="dark horizontal my-0">
            <div class="card-footer p-3">
                <p class="mb-0"><span class="text-success text-sm font-weight-bolder">Currency </span>@Default.DefaultCurrency</p>
            </div>
        </div>
    </div>


    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <a href="@topUpUrl">
            <div class="card">
                <div class="card-header p-3 pt-2">
                    <div class="icon icon-lg icon-shape bg-gradient-dark shadow-dark text-center border-radius-xl mt-n4 position-absolute">
                        <i class="material-icons opacity-10">+</i>
                    </div>
                    <div class="text-end pt-1">
                        <p class="text-sm mb-0 text-capitalize"></p>
                        <h4 class="mb-0">Top Up Wallet</h4>
                    </div>
                </div>
                <hr class="dark horizontal my-0">
                <div class="card-footer p-3">
                    <p class="mb-0"><span class="text-success text-sm font-weight-bolder">Add Funds </span>To Your Wallet</p>
                </div>
            </div>
        </a>
    </div>

    <div class="col-12">
        <h1 style="text-align:center;">
            Wallet Top Ups
        </h1>
    </div>

    <hr style="height: 2px; border: 2px solid #344767;" />
</div>
<div class="row">
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Top Ups</h6>
                </div>
            </div>
            <div class="card-body px-0 pb-2">
                <div class="table-responsive p-0">
                    <table class="table align-items-center justify-content-center mb-0" id="floatPaymentTable">
                        <thead>
                            <tr>
                                <th></th>
                                <th style="text-align:center">Id</th>
                                <th style="text-align:center">Currency</th>
                                <th style="text-align:center">Amount</th>
                                <th style="text-align:center">Status</th>
                                <th style="text-align:center">Balance</th>
                                <th style="text-align:center">Reference</th>
                                <th style="text-align:center">Created Date</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var floatPayment in Model.Float.FloatPayments)
                            {
                                <tr>
                                    <td>
                                        <div>
                                            <img src="/expensewallet/img/bank-account.png" class="avatar avatar-sm rounded-circle me-2" alt="spotify" style="padding:5px;">
                                        </div>
                                    </td>
                                    <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.Id</h6>
                                    </td>
                                    <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.Currency</h6>
                                    </td>
                                    <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.Amount</h6>
                                    </td>
                                        <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.Status</h6>
                                    </td>
                                    <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.Balance</h6>

                                    </td>
                                    <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.Reference</h6>
                                    </td>
                                    <td>
                                        <h6 class="mb-0 text-sm" style="text-align:center;">@floatPayment.CreatedDate</h6>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function() {
            $('#floatPaymentTable').dataTable();
        });
    </script>
}